defaults:
  # - optimizer/SGD
  - callbacks/callbacks

device: ${device}

_target_: ACIL.trainer.trainer.Trainer
output_dir: models
save_last: False

eval_at_end: False
optimizer:

epochs: 10

verbose: False
