defaults:
  - main
  - trainer: trainer
  - trainer/optimizer@trainer.optimizer: Adam
  - trainer/callbacks/eval: stop
  - data: activelearning
  - model: queryaftertrain
  - model/criterions@model.criterion: CrossEntropy
  - data/sampler@data.dataloaders.train_loader.sampler: MinMaxROS
  - _self_

trainer:
  iterations: 1
  epochs: 200
  optimizer:
    lr: 0.0015

data:
  query:
    n_samples: 1000
    limit_inferences: False
    
model:
  reload_model_on_new_classes: False
  network:
    freeze: True