defaults:
  - main
  # - trainer: trainer Frozen
  # - trainer: finetuned Better
  - trainer/optimizer@trainer.optimizer: Adam
  # - trainer/scheduler: StepLR Frozen
  - trainer/callbacks/eval: stop
  - data: activelearning
  # - model: queryaftertrain Frozen
  # - model: steppedmodelAL Better
  - model/criterions@model.criterion: CrossEntropy
  - data/sampler@data.dataloaders.train_loader.sampler: MinMaxROS
  - _self_

trainer:
  iterations: 1
  epochs: 200
  optimizer:
    lr: 0.0015

data:
  query:
    n_samples: 1000
    limit_inferences: False
    
model:
  reload_model_on_new_classes: False
  network:
    freeze: True